name: build_develop_version

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: write # 赋予修改 Release 的权限

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Call Setup NVGT Action
      uses: ./.github/actions/setup-nvgt
      with:
        dev: 'true'
        add-to-path: 'true'

    - name: create_sound_pack
      shell: bash
      run: |
        nvgt "${{ github.workspace }}/pack_creater.nvgt" use_file

    - name: build windows client
      shell: bash
      run: |
        nvgt --compile-debug -pwindows "${{ github.workspace }}/tk.nvgt"

    - name: build windows server
      shell: bash
      run: |
        nvgt --compile-debug -pwindows "${{ github.workspace }}/server/tkserver.nvgt"

    - name: build linux server
      shell: bash
      run: |
        nvgt --compile-debug -p linux "${{ github.workspace }}/server/tkserver.nvgt"

    - name: Update Release Tag
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git tag -d latest-develop-version || true
        git push origin :refs/tags/latest-develop-version || true
        git tag latest-develop-version
        git push origin latest-develop-version

    - name: Update Latest Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "latest-develop-version"
        name: "latest develop version"
        body: |
          Commit SHA: ${{ github.sha }}
          Message: ${{ github.event.head_commit.message }}
        prerelease: true
        overwrite: true
        files: |
          ${{ github.workspace }}/server/tkserver.zip
          ${{ github.workspace }}/server/tkserver.tar.gz
          ${{ github.workspace }}/tk.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
